name: pruebatecnicalaravel
recipe: laravel
config:
  php: '8.2'
  webroot: public
  xdebug: true
tooling:
  phpunit:
    service: appserver
    cmd: ./vendor/bin/phpunit
  pest:
    service: appserver
    cmd: ./vendor/bin/pest
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd: ./vendor/bin/behat
