name: pruebatecnicalaravel
recipe: laravel
config:
  webroot: public
services:
  node:
    type: node:20
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
